### ISSUE TITLE
Compilation error encountered on nvidia-docker with cuda version 12.0

### ISSUE THREAD

**Issue by jiashuy** [NVIDIA-Merlin/HierarchicalKV#100]
When I compiled this project on nvidia-docker with cuda version 12.0, I got this error message:
 
======================================   Error log ======================================         
......
[ 81%] Linking CXX executable **merlin_hashtable_test**
/usr/bin/ld: CMakeFiles/merlin_hashtable_benchmark.dir/benchmark/merlin_hashtable_benchmark.cc.cu.o: in function \`nv::merlin::HashTable<unsigned long, float, unsigned long>::insert_or_assign(unsigned long, unsigned long const*, float const*, unsigned long const*, CUstream_st*, bool)':
......
/Workspace/HierarchicalKV/include/merlin_hashtable.cuh:1131: undefined reference to \`nv::merlin::HashTable<unsigned long, float, unsigned long>::thrust_par'
collect2: error: ld returned 1 exit status
......
======================================   Error log ======================================
Even though I replaced the header file related to **thrust** with absolute path, I got the same error.
But when I used nvidia-docker with cuda version 11.7.0 to compile this project, the error mentioned above disappeared.

**Comment by rhdong** [comment]
Hi @jiashuy , could you provide the information about the compiling docker container? Especially, please check the thrust version in your docker, thank you!

**Comment by jiashuy** [comment]
Thanks. Its due to the version of the nvidia-docker's env. After changing other docker images, this problem disappeared.
