### ISSUE TITLE
[Bug] insert_and_evict got wrong outputs

### ISSUE THREAD

**Issue by Lifann** [NVIDIA-Merlin/HierarchicalKV#110]
There are some bugs in the test case, and the eviction is not triggered.
After fix the condition, the test case will fail:
https://github.com/Lifann/HierarchicalKV/commit/300eb1fe3cc195117e55ee2d12b81a58444659cf

**Comment by rhdong** [comment]
https://github.com/NVIDIA-Merlin/HierarchicalKV/pull/112
