### ISSUE TITLE
[Feature request] Add a new contain API for cache senario

### ISSUE THREAD

**Issue by Lifann** [NVIDIA-Merlin/HierarchicalKV#176]
We use pure-device hkv as a device cache for feature ids which has high probability to be used in next few steps training/inference. It's critical to have a `contain` API for performance if there are multiple level of caches, in different throughput, interact with each other:
```cpp
  void contain(const size_type n, const key_type* keys,  // (n)
               bool* founds,                             // (n)
               score_type* scores = nullptr,             // (n)
               cudaStream_t stream = 0) const;
```

**Comment by rhdong** [comment]
Close by https://github.com/NVIDIA-Merlin/HierarchicalKV/pull/177
