### ISSUE TITLE
[Feature Request] Support runtime setting to embedding vector dimension

### ISSUE THREAD

**Issue by zehuanw** [NVIDIA-Merlin/HierarchicalKV#65]
It's inconvenient to the users if they need to recompile HKV to use new embedding vector size. On the other hand, if we list all the possible vector size in compile time will make our binary very big.

Shall we consider to support runtime setting to embedding vector dimension?

https://github.com/NVIDIA-Merlin/HierarchicalKV/issues/65#tasklist-block-d2735aaa-05f0-4a9a-a9ca-cc31faf02a46

**Comment by rhdong** [comment]
This Feature request has been merged in https://github.com/NVIDIA-Merlin/HierarchicalKV/pull/87, thank you!
