### ISSUE TITLE
Has eviction strategy been implemented for hierarchical kv?

### ISSUE THREAD

**Issue by Gscim** [NVIDIA-Merlin/HierarchicalKV#92]
Will there be memory exchange between hbm and hmem ? Thanks.

**Comment by rhdong** [comment]
Hi @Gscim, thank you for your question, before the commit https://github.com/NVIDIA-Merlin/HierarchicalKV/pull/91, the evict mechanism has some bugs indeed. About the exchange between HBM and HMEM, maybe you mean the hot-cold key mechanism that is under development and will come soon.  If I misunderstand something, please feel free to correct me. Thank you again!

**Comment by rhdong** [comment]
Close for a long time no reply, and please feel free to reopen it any time. Thanks!
